---

- name: update web servers
  hosts: nodes
  become: yes
      
  tasks:


  - name: init password jenkin
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    changed_when: false
    register: result


  - name: print init password jenkins
    debug:
      var: result.stdout
      


...
